[package]
version = "0.1.4"
name = "fetch-hash"
description = "Renamed. Please use 'fetch-data' instead"
repository = "https://github.com/CarlKCarlK/fetch-data"
readme = "README.md"
documentation = "https://docs.rs/fetch-hash/latest/fetch-data/"
authors = ["Carl Kadie"]
exclude = ["tests/data/*"]
license = "Apache-2.0"
keywords = ["testing", "data", "web", "request"]
categories = ["science"]
homepage = "https://github.com/CarlKCarlK/fetch-data"
edition = "2021"
